# Generated by Django 4.0.5 on 2022-07-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0002_ad_nastaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='nastaran',
        ),
    ]
