# Generated by Django 4.0.5 on 2022-07-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0003_remove_ad_nastaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img_url',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
