# Generated by Django 4.0.5 on 2022-07-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0004_alter_ad_img_url_alter_ad_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickedCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewedCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.AlterField(
            model_name='ad',
            name='approve',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_time', models.DateTimeField(verbose_name='date viewed')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertisement.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_time', models.DateTimeField(verbose_name='date clicked')),
                ('Ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertisement.ad')),
            ],
        ),
    ]
