# Generated by Django 4.0.5 on 2022-07-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisement', '0005_clickedcount_viewedcount_remove_ad_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickedcount',
            name='ad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Advertisement.ad'),
        ),
        migrations.AddField(
            model_name='clickedcount',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='viewedcount',
            name='ad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Advertisement.ad'),
        ),
        migrations.AddField(
            model_name='viewedcount',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
